{
 "title": "Übersicht Solar",
 "tags": [ "ok" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Watt",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "watt", "legendFormat": "Watt (WEB)" },
    {
     "expr": "sum ((current{} * voltage{}) > 0) < 900",
     "legendFormat": "Watt (API)"
    }
   ]
  },
  {
   "title": "Online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 0 },
   "targets": [
    { "expr": "online", "legendFormat": "online" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_e", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Spannung",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "(voltage > -1) <100", "legendFormat": "Panel {{panel}}" }
   ]
  },
  {
   "title": "Strom",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "current > -1 < 100", "legendFormat": "Panel {{panel}}" }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(current{} * voltage{}) > 0 <2000",
     "legendFormat": "Panel {{panel}}"
    }
   ]
  },
  {
   "title": "Abfragezeit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    { "expr": "executiontime", "legendFormat": "Zeit" }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature != (-10.00)", "legendFormat": "Temperatur" }
   ]
  }
 ]
}